### ISSUE TITLE
Failed to run `eth-block`

### ISSUE THREAD

**Issue by pbeza** [risc0/zeth#34]
I would like to use `zeth` to bake demo code that reads a series of transactions as input and outputs the resulting block hash. It looks like you've already prepared this kind of demo here:
https://github.com/risc0/zeth/blob/main/guests/eth-block/src/main.rs

Unfortunately I fail to make use of it. My attempt to run it:
```
ubuntu@VM-0-6-ubuntu:~/zeth/guests/eth-block$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/eth-block`
thread '<unnamed>' panicked at 'not implemented', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-platform-0.18.0/src/syscall.rs:224:1
stack backtrace:
   0:     0x55c85bc9e86a - std::backtrace_rs::backtrace::libunwind::trace::h95061b614921b6ff
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c85bc9e86a - std::backtrace_rs::backtrace::trace_unsynchronized::hf451b1d73b4bdad4
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c85bc9e86a - std::sys_common::backtrace::_print_fmt::h9fca4c77375a2dbe
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55c85bc9e86a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb32a52511e633a9b
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55c85bcbbaae - core::fmt::write::hb58172bccf5a732a
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/fmt/mod.rs:1232:17
   5:     0x55c85bc9c9f5 - std::io::Write::write_fmt::hc477a162dd78515a
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/io/mod.rs:1684:15
   6:     0x55c85bc9e635 - std::sys_common::backtrace::_print::hc9c29ec89e5d88cd
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55c85bc9e635 - std::sys_common::backtrace::print::h641a35e35def21bb
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55c85bc9f93f - std::panicking::default_hook::{{closure}}::h6f17652ca069c908
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:271:22
   9:     0x55c85bc9f67b - std::panicking::default_hook::h33fe72da8bfd0e11
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:290:9
  10:     0x55c85bc9fee8 - std::panicking::rust_panic_with_hook::haf1dd3d09ecba84d
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:692:13
  11:     0x55c85bc9fda2 - std::panicking::begin_panic_handler::{{closure}}::h2657be74b6192e09
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:581:13
  12:     0x55c85bc9ecd6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6bee8db45459b0a6
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55c85bc9faf2 - rust_begin_unwind
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:579:5
  14:     0x55c85b8f9b73 - core::panicking::panic_fmt::hd40b690c85fbbb1d
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/panicking.rs:64:14
  15:     0x55c85b8f9c0d - core::panicking::panic::h2c093a338a41f38f
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/panicking.rs:114:5
  16:     0x55c85bc87708 - syscall_2
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-platform-0.18.0/src/syscall.rs:217:13
  17:     0x55c85bc873b4 - risc0_zkvm_platform::syscall::sys_read_internal::h8ad8760c2dbfe7d6
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-platform-0.18.0/src/syscall.rs:518:13
  18:     0x55c85bc872af - risc0_zkvm_platform::syscall::sys_read_words::hb794065292e73493
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-platform-0.18.0/src/syscall.rs:503:5
  19:     0x55c85bc6428a - <risc0_zkvm::guest::env::FdReader as risc0_zkvm::serde::deserializer::WordRead>::read_words::ha0c1443bcaba8244
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/guest/env.rs:249:36
  20:     0x55c85ba4685b - <&mut R as risc0_zkvm::serde::deserializer::WordRead>::read_words::hbc9cafdbb7607a3a
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:39:9
  21:     0x55c85b90c06d - risc0_zkvm::serde::deserializer::Deserializer<R>::try_take_word::h6b9b98bef062984f
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:202:9
  22:     0x55c85b90d6c3 - <&mut risc0_zkvm::serde::deserializer::Deserializer<R> as serde::de::Deserializer>::deserialize_bytes::h0389a0b44e2086dd
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:341:25
  23:     0x55c85b9630b2 - alloy_primitives::bits::serde::<impl serde::de::Deserialize for alloy_primitives::bits::fixed::FixedBytes<_>>::deserialize::h3010ed5d98f3cc61
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/alloy-primitives-0.3.3/src/bits/serde.rs:65:13
  24:     0x55c85b93fc95 - <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::h4c41d3886b403fac
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.171/src/de/mod.rs:792:9
  25:     0x55c85b912c18 - <risc0_zkvm::serde::deserializer::SeqAccess<R> as serde::de::SeqAccess>::next_element_seed::hf78689e056d050e5
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:111:21
  26:     0x55c85b90f916 - serde::de::SeqAccess::next_element::h80fa4759aa2ef15e
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.171/src/de/mod.rs:1731:9
  27:     0x55c85b925c6a - <zeth_primitives::block::_::<impl serde::de::Deserialize for zeth_primitives::block::Header>::deserialize::__Visitor as serde::de::Visitor>::visit_seq::h88b6049b04422057
                               at /home/ubuntu/zeth/primitives/src/block.rs:25:50
  28:     0x55c85b90e35f - <&mut risc0_zkvm::serde::deserializer::Deserializer<R> as serde::de::Deserializer>::deserialize_tuple::h28b1493643573e77
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:404:9
  29:     0x55c85b90ee2c - <&mut risc0_zkvm::serde::deserializer::Deserializer<R> as serde::de::Deserializer>::deserialize_struct::h7b8283f1d0ad2707
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:442:9
  30:     0x55c85b925c30 - zeth_primitives::block::_::<impl serde::de::Deserialize for zeth_primitives::block::Header>::deserialize::h450700b44013782e
                                 at /home/ubuntu/zeth/primitives/src/block.rs:25:50
  31:     0x55c85b93fed5 - <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::hd360538895e99cb6
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.171/src/de/mod.rs:792:9
  32:     0x55c85b911cab - <risc0_zkvm::serde::deserializer::SeqAccess<R> as serde::de::SeqAccess>::next_element_seed::h84fe1f19dbdd07ed
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:111:21
  33:     0x55c85b90f696 - serde::de::SeqAccess::next_element::h19c97ecf78808123
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.171/src/de/mod.rs:1731:9
  34:     0x55c85b97a073 - <zeth_lib::input::_::<impl serde::de::Deserialize for zeth_lib::input::Input<E>>::deserialize::__Visitor<E> as serde::de::Visitor>::visit_seq::h204d1b4526b4dbb8
                               at /home/ubuntu/zeth/lib/src/input.rs:31:33
  35:     0x55c85b90e39f - <&mut risc0_zkvm::serde::deserializer::Deserializer<R> as serde::de::Deserializer>::deserialize_tuple::h61732905f4f86d38
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:404:9
  36:     0x55c85b90eabc - <&mut risc0_zkvm::serde::deserializer::Deserializer<R> as serde::de::Deserializer>::deserialize_struct::h34fcd07908594780
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/serde/deserializer.rs:442:9
  37:     0x55c85b97b1f0 - zeth_lib::input::_::<impl serde::de::Deserialize for zeth_lib::input::Input<E>>::deserialize::h9f4757b4361869de
                               at /home/ubuntu/zeth/lib/src/input.rs:31:33
  38:     0x55c85ba468c5 - <risc0_zkvm::guest::env::FdReader as risc0_zkvm::guest::env::Read>::read::hd19d9f809420e3fa
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/guest/env.rs:231:9
  39:     0x55c85ba46775 - risc0_zkvm::guest::env::read::h192e8209a443c704
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/guest/env.rs:91:5
  40:     0x55c85b93c9bf - eth_block::main::h95b60fc4cd30742e
                               at /home/ubuntu/zeth/guests/eth-block/src/main.rs:24:17
  41:     0x55c85b979ad6 - main
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-0.18.0/src/guest/mod.rs:156:17
  42:     0x7fd5e2c29d90 - <unknown>
  43:     0x7fd5e2c29e40 - __libc_start_main
  44:     0x55c85b8fa1a5 - _start
  45:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

Other attempt:
```
ubuntu@VM-0-6-ubuntu:~/zeth/guests/eth-block$ RUST_BACKTRACE=full target/release/eth-block
thread '<unnamed>' panicked at 'not implemented', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/risc0-zkvm-platform-0.18.0/src/syscall.rs:224:1
stack backtrace:
   0:     0x55cf991113ea - std::backtrace_rs::backtrace::libunwind::trace::h95061b614921b6ff
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cf991113ea - std::backtrace_rs::backtrace::trace_unsynchronized::hf451b1d73b4bdad4
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cf991113ea - std::sys_common::backtrace::_print_fmt::h9fca4c77375a2dbe
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55cf991113ea - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb32a52511e633a9b
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cf9912a86e - core::fmt::write::hb58172bccf5a732a
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/fmt/mod.rs:1232:17
   5:     0x55cf9910f575 - std::io::Write::write_fmt::hc477a162dd78515a
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/io/mod.rs:1684:15
   6:     0x55cf991111b5 - std::sys_common::backtrace::_print::hc9c29ec89e5d88cd
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55cf991111b5 - std::sys_common::backtrace::print::h641a35e35def21bb
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55cf9911239f - std::panicking::default_hook::{{closure}}::h6f17652ca069c908
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:271:22
   9:     0x55cf991120db - std::panicking::default_hook::h33fe72da8bfd0e11
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:290:9
  10:     0x55cf99112948 - std::panicking::rust_panic_with_hook::haf1dd3d09ecba84d
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:692:13
  11:     0x55cf99112802 - std::panicking::begin_panic_handler::{{closure}}::h2657be74b6192e09
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:581:13
  12:     0x55cf99111856 - std::sys_common::backtrace::__rust_end_short_backtrace::h6bee8db45459b0a6
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55cf99112552 - rust_begin_unwind
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:579:5
  14:     0x55cf9901a283 - core::panicking::panic_fmt::hd40b690c85fbbb1d
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/panicking.rs:64:14
  15:     0x55cf9901a31d - core::panicking::panic::h2c093a338a41f38f
                               at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/panicking.rs:114:5
  16:     0x55cf990fa7c6 - risc0_zkvm_platform::syscall::sys_read_words::h1c41f918ad0c2555
  17:     0x55cf990f58ec - <risc0_zkvm::guest::env::FdReader as risc0_zkvm::serde::deserializer::WordRead>::read_words::hd8694ed457b78ad3
Aborted (core dumped)
```
Can you please guide me on how is it supposed to be run? I guess I'm missing something very fundamental here as there is `#![no_main]` in the above code:
https://github.com/risc0/zeth/blob/202222a08387b8143b2b1c378a27c7d0a16e0c33/guests/eth-block/src/main.rs#L15
I guess I should run the above code with your zkVM but I have no idea how to do it. Do you have any docs so I can learn more about `zeth`?

Tagging @hashcashier as the [co-author of the above file](https://github.com/risc0/zeth/blame/202222a08387b8143b2b1c378a27c7d0a16e0c33/guests/eth-block/src/main.rs) (to get your attention). Thanks!

**Comment by hashcashier** [comment]
@pbeza It seems like you're trying to run the "guest" binary directly as an executable, which isn't supported. You'll have to run the "host" zeth binary, which takes care of preparing the necessary data for the guest to function and running it inside the executor. You'll find plenty of details in the main repository readme on how to run zeth, and you can take a look at its source for more details on the execution flow:
https://github.com/risc0/zeth/blob/202222a08387b8143b2b1c378a27c7d0a16e0c33/host/src/main.rs

**Comment by pbeza** [comment]
Gotcha, thank you @hashcashier for the quick response!

Just one more question, so that I can better understand the whole flow – can you please pinpoint the code where this function:
https://github.com/risc0/zeth/blob/202222a08387b8143b2b1c378a27c7d0a16e0c33/guests/eth-block/src/main.rs#L22
is being called? I'm bit confused how host-guest dependency.

**Comment by hashcashier** [comment]
@pbeza 
The guest is a standard [risc-zero zkVM](https://github.com/risc0/risc0) guest binary.

The crates for the guests get compiled down into risc-v bytecode by the risc0-build crate.
https://github.com/risc0/zeth/blob/202222a08387b8143b2b1c378a27c7d0a16e0c33/guests/build.rs#L15-L17

That bytecode is then embedded into the zeth-guests crate:
https://github.com/risc0/zeth/blob/202222a08387b8143b2b1c378a27c7d0a16e0c33/guests/src/lib.rs#L15

The bytecode is then referenced as follows in the host code:
https://github.com/risc0/zeth/blob/202222a08387b8143b2b1c378a27c7d0a16e0c33/host/src/main.rs#L30-L32

The host then uses the risc0 executor to run the bytecode using some input:
https://github.com/risc0/zeth/blob/202222a08387b8143b2b1c378a27c7d0a16e0c33/host/src/main.rs#L286
